# Generated by Django 4.2.9 on 2026-10-02 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_goods_lifecycle_status_goods_retention_expire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestructionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=40, unique=True, verbose_name='计划编号')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='拟销毁日期')),
                ('reason', models.TextField(blank=True, verbose_name='销毁事由')),
                ('status', models.CharField(choices=[('planned', '销毁计划'), ('reviewed', '资格复核'), ('approved', '已批准'), ('executed', '已执行'), ('abandoned', '已终止')], default='planned', max_length=20, verbose_name='计划状态')),
                ('review_remark', models.TextField(blank=True, verbose_name='复核意见')),
                ('approval_remark', models.TextField(blank=True, verbose_name='批准意见')),
                ('execute_remark', models.TextField(blank=True, verbose_name='执行备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='计划制定人')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='执行确认人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '销毁计划',
                'verbose_name_plural': '销毁计划',
                'db_table': 'ds_destruction_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=50, verbose_name='列入时物资编码')),
                ('goods_name', models.CharField(max_length=200, verbose_name='列入时物资名称')),
                ('quantity_at_plan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='列入时库存数量')),
                ('status', models.CharField(choices=[('included', '已列入'), ('eligible', '复核合格'), ('excluded', '复核剔除'), ('approved', '批准销毁'), ('rejected', '批准拒绝'), ('blocked', '执行拦截'), ('destroyed', '已销毁')], default='included', max_length=20, verbose_name='条目状态')),
                ('block_reasons', models.JSONField(blank=True, default=list, verbose_name='拦截原因')),
                ('plan_warnings', models.JSONField(blank=True, default=list, verbose_name='列入时风险提示')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('destroyed_at', models.DateTimeField(blank=True, null=True, verbose_name='销毁时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destruction_items', to='warehouse.goods', verbose_name='物资')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='destruction.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁清单条目',
                'verbose_name_plural': '销毁清单条目',
                'db_table': 'ds_destruction_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DestructionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='更正字段')),
                ('old_value', models.TextField(blank=True, verbose_name='更正前值')),
                ('new_value', models.TextField(blank=True, verbose_name='更正后值')),
                ('reason', models.TextField(verbose_name='更正原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更正时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destruction_corrections', to='warehouse.goods', verbose_name='物资')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='destruction.destructionitem', verbose_name='销毁条目')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_corrections', to=settings.AUTH_USER_MODEL, verbose_name='更正人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='destruction.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁后元数据更正',
                'verbose_name_plural': '销毁后元数据更正',
                'db_table': 'ds_destruction_correction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionStageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('planning', '销毁计划'), ('review', '资格复核'), ('approval', '批准'), ('execution', '执行确认')], max_length=20, verbose_name='阶段')),
                ('summary', models.JSONField(default=dict, verbose_name='清单摘要')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='摘要校验值')),
                ('note', models.TextField(blank=True, verbose_name='阶段备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='destruction.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁阶段清单快照',
                'verbose_name_plural': '销毁阶段清单快照',
                'db_table': 'ds_stage_snapshot',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['plan', 'stage'], name='ds_stage_sn_plan_id_75a44e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='destructionitem',
            constraint=models.UniqueConstraint(fields=('plan', 'goods'), name='uniq_goods_per_destruction_plan'),
        ),
    ]
