# Generated by Django 4.2.9 on 2026-10-02 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='lifecycle_status',
            field=models.CharField(choices=[('in_custody', '在库'), ('destroyed', '已销毁')], default='in_custody', max_length=20, verbose_name='生命周期状态'),
        ),
        migrations.AddField(
            model_name='goods',
            name='retention_expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='保管期限届满日'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='warehouse.variety', verbose_name='所属品种'),
        ),
        migrations.CreateModel(
            name='GoodsHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('freeze', '冻结'), ('investigation', '未结调查')], max_length=20, verbose_name='管控类型')),
                ('reason', models.TextField(blank=True, verbose_name='发起原因')),
                ('status', models.CharField(choices=[('active', '生效中'), ('released', '已解除')], default='active', max_length=20, verbose_name='状态')),
                ('release_reason', models.TextField(blank=True, verbose_name='解除原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_holds', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='warehouse.goods', verbose_name='货物')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_goods_holds', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
            ],
            options={
                'verbose_name': '物资管控记录',
                'verbose_name_plural': '物资管控记录',
                'db_table': 'wh_goods_hold',
                'ordering': ['-created_at'],
            },
        ),
    ]
