# Generated by Django 4.2.9 on 2026-10-02 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestructionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=30, unique=True, verbose_name='计划编号')),
                ('title', models.CharField(max_length=100, verbose_name='计划名称')),
                ('status', models.CharField(choices=[('planning', '待复核'), ('reviewed', '待批准'), ('approved', '待执行'), ('rejected', '已驳回'), ('executed', '已执行')], default='planning', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('review_remark', models.CharField(blank=True, max_length=300, verbose_name='复核意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('approve_remark', models.CharField(blank=True, max_length=300, verbose_name='批准意见')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_destruction_plans', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '销毁计划',
                'verbose_name_plural': '销毁计划',
                'db_table': 'wh_destruction_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='custody_until',
            field=models.DateField(blank=True, null=True, verbose_name='保管期限届满日'),
        ),
        migrations.AddField(
            model_name='goods',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='冻结原因'),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='调查事项')),
                ('status', models.CharField(choices=[('open', '调查中'), ('closed', '已结案')], default='open', max_length=20, verbose_name='状态')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='立案时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_investigations', to=settings.AUTH_USER_MODEL, verbose_name='结案人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='warehouse.goods', verbose_name='货物')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_investigations', to=settings.AUTH_USER_MODEL, verbose_name='立案人')),
            ],
            options={
                'verbose_name': '调查记录',
                'verbose_name_plural': '调查记录',
                'db_table': 'wh_investigation',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='销毁数量')),
                ('reason', models.CharField(max_length=200, verbose_name='销毁原因')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='销毁方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('eligible', '复核通过'), ('ineligible', '复核不通过'), ('destroyed', '已销毁'), ('blocked', '执行拦截'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='状态')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='复核结论')),
                ('execute_note', models.CharField(blank=True, max_length=300, verbose_name='执行说明')),
                ('destroyed_at', models.DateTimeField(blank=True, null=True, verbose_name='销毁时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destruction_items', to='warehouse.goods', verbose_name='货物')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁计划明细',
                'verbose_name_plural': '销毁计划明细',
                'db_table': 'wh_destruction_plan_item',
                'ordering': ['id'],
                'unique_together': {('plan', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='DestructionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(verbose_name='更正内容')),
                ('reason', models.CharField(max_length=300, verbose_name='更正原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更正时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_corrections', to=settings.AUTH_USER_MODEL, verbose_name='更正人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='warehouse.destructionplanitem', verbose_name='销毁明细')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='warehouse.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁更正',
                'verbose_name_plural': '销毁更正',
                'db_table': 'wh_destruction_correction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionStageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('plan', '销毁计划'), ('review', '资格复核'), ('approve', '批准'), ('execute', '执行确认')], max_length=20, verbose_name='阶段')),
                ('summary', models.JSONField(verbose_name='清单摘要')),
                ('digest', models.CharField(max_length=64, verbose_name='摘要值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='warehouse.destructionplan', verbose_name='销毁计划')),
            ],
            options={
                'verbose_name': '销毁阶段清单摘要',
                'verbose_name_plural': '销毁阶段清单摘要',
                'db_table': 'wh_destruction_stage_snapshot',
                'ordering': ['created_at'],
                'unique_together': {('plan', 'stage')},
            },
        ),
    ]
